/**
 * Axon global CLI options + web executor constraints.
 *
 * Split from axon-command-map.ts to stay under monolith line limit.
 * Re-exported from axon-command-map.ts for convenience.
 */

import type { AxonOptionSpec } from './axon-command-map'

export const AXON_GLOBAL_OPTIONS: ReadonlyArray<AxonOptionSpec> = [
  { key: 'start_url', flag: '--start-url', value: 'string', scope: 'global' },
  { key: 'max_pages', flag: '--max-pages', value: 'number', scope: 'global' },
  { key: 'max_depth', flag: '--max-depth', value: 'number', scope: 'global' },
  { key: 'include_subdomains', flag: '--include-subdomains', value: 'bool', scope: 'global' },
  { key: 'exclude_path_prefix', flag: '--exclude-path-prefix', value: 'list', scope: 'global' },
  { key: 'output_dir', flag: '--output-dir', value: 'string', scope: 'global' },
  { key: 'output', flag: '--output', value: 'string', scope: 'global' },
  { key: 'render_mode', flag: '--render-mode', value: 'enum', scope: 'global' },
  { key: 'chrome_remote_url', flag: '--chrome-remote-url', value: 'string', scope: 'global' },
  { key: 'chrome_proxy', flag: '--chrome-proxy', value: 'string', scope: 'global' },
  { key: 'chrome_user_agent', flag: '--chrome-user-agent', value: 'string', scope: 'global' },
  { key: 'chrome_headless', flag: '--chrome-headless', value: 'bool', scope: 'global' },
  { key: 'chrome_anti_bot', flag: '--chrome-anti-bot', value: 'bool', scope: 'global' },
  { key: 'chrome_intercept', flag: '--chrome-intercept', value: 'bool', scope: 'global' },
  { key: 'chrome_stealth', flag: '--chrome-stealth', value: 'bool', scope: 'global' },
  { key: 'chrome_bootstrap', flag: '--chrome-bootstrap', value: 'bool', scope: 'global' },
  {
    key: 'chrome_bootstrap_timeout_ms',
    flag: '--chrome-bootstrap-timeout-ms',
    value: 'number',
    scope: 'global',
  },
  {
    key: 'chrome_bootstrap_retries',
    flag: '--chrome-bootstrap-retries',
    value: 'number',
    scope: 'global',
  },
  { key: 'respect_robots', flag: '--respect-robots', value: 'bool', scope: 'global' },
  { key: 'min_markdown_chars', flag: '--min-markdown-chars', value: 'number', scope: 'global' },
  { key: 'drop_thin_markdown', flag: '--drop-thin-markdown', value: 'bool', scope: 'global' },
  { key: 'discover_sitemaps', flag: '--discover-sitemaps', value: 'bool', scope: 'global' },
  { key: 'cache', flag: '--cache', value: 'bool', scope: 'global' },
  { key: 'cache_skip_browser', flag: '--cache-skip-browser', value: 'bool', scope: 'global' },
  { key: 'format', flag: '--format', value: 'enum', scope: 'global' },
  { key: 'limit', flag: '--limit', value: 'number', scope: 'global' },
  { key: 'query', flag: '--query', value: 'string', scope: 'global' },
  { key: 'urls', flag: '--urls', value: 'string', scope: 'global' },
  { key: 'url_glob', flag: '--url-glob', value: 'list', scope: 'global' },
  { key: 'embed', flag: '--embed', value: 'bool', scope: 'global' },
  { key: 'collection', flag: '--collection', value: 'string', scope: 'global' },
  { key: 'batch_concurrency', flag: '--batch-concurrency', value: 'number', scope: 'global' },
  { key: 'wait', flag: '--wait', value: 'bool', scope: 'global' },
  { key: 'yes', flag: '--yes', value: 'bool', scope: 'global' },
  { key: 'json', flag: '--json', value: 'bool', scope: 'global' },
  { key: 'performance_profile', flag: '--performance-profile', value: 'enum', scope: 'global' },
  { key: 'concurrency_limit', flag: '--concurrency-limit', value: 'number', scope: 'global' },
  {
    key: 'crawl_concurrency_limit',
    flag: '--crawl-concurrency-limit',
    value: 'number',
    scope: 'global',
  },
  {
    key: 'backfill_concurrency_limit',
    flag: '--backfill-concurrency-limit',
    value: 'number',
    scope: 'global',
  },
  { key: 'sitemap_only', flag: '--sitemap-only', value: 'bool', scope: 'global' },
  { key: 'delay_ms', flag: '--delay-ms', value: 'number', scope: 'global' },
  { key: 'request_timeout_ms', flag: '--request-timeout-ms', value: 'number', scope: 'global' },
  { key: 'fetch_retries', flag: '--fetch-retries', value: 'number', scope: 'global' },
  { key: 'retry_backoff_ms', flag: '--retry-backoff-ms', value: 'number', scope: 'global' },
  { key: 'shared_queue', flag: '--shared-queue', value: 'bool', scope: 'global' },
  { key: 'pg_url', flag: '--pg-url', value: 'string', scope: 'global' },
  { key: 'redis_url', flag: '--redis-url', value: 'string', scope: 'global' },
  { key: 'amqp_url', flag: '--amqp-url', value: 'string', scope: 'global' },
  { key: 'crawl_queue', flag: '--crawl-queue', value: 'string', scope: 'global' },
  { key: 'extract_queue', flag: '--extract-queue', value: 'string', scope: 'global' },
  { key: 'embed_queue', flag: '--embed-queue', value: 'string', scope: 'global' },
  { key: 'ingest_queue', flag: '--ingest-queue', value: 'string', scope: 'global' },
  { key: 'tei_url', flag: '--tei-url', value: 'string', scope: 'global' },
  { key: 'qdrant_url', flag: '--qdrant-url', value: 'string', scope: 'global' },
  { key: 'openai_base_url', flag: '--openai-base-url', value: 'string', scope: 'global' },
  { key: 'openai_api_key', flag: '--openai-api-key', value: 'string', scope: 'global' },
  { key: 'openai_model', flag: '--openai-model', value: 'string', scope: 'global' },
  {
    key: 'watchdog_stale_timeout_secs',
    flag: '--watchdog-stale-timeout-secs',
    value: 'number',
    scope: 'global',
  },
  {
    key: 'watchdog_confirm_secs',
    flag: '--watchdog-confirm-secs',
    value: 'number',
    scope: 'global',
  },
  { key: 'cron_every_seconds', flag: '--cron-every-seconds', value: 'number', scope: 'global' },
  { key: 'cron_max_runs', flag: '--cron-max-runs', value: 'number', scope: 'global' },
  { key: 'normalize', flag: '--normalize', value: 'bool', scope: 'global' },
  {
    key: 'chrome_network_idle_timeout',
    flag: '--chrome-network-idle-timeout',
    value: 'number',
    scope: 'global',
  },
  {
    key: 'auto_switch_thin_ratio',
    flag: '--auto-switch-thin-ratio',
    value: 'number',
    scope: 'global',
  },
  {
    key: 'auto_switch_min_pages',
    flag: '--auto-switch-min-pages',
    value: 'number',
    scope: 'global',
  },
  { key: 'url_whitelist', flag: '--url-whitelist', value: 'list', scope: 'global' },
  { key: 'block_assets', flag: '--block-assets', value: 'bool', scope: 'global' },
  { key: 'max_page_bytes', flag: '--max-page-bytes', value: 'number', scope: 'global' },
  {
    key: 'redirect_policy_strict',
    flag: '--redirect-policy-strict',
    value: 'bool',
    scope: 'global',
  },
  {
    key: 'chrome_wait_for_selector',
    flag: '--chrome-wait-for-selector',
    value: 'string',
    scope: 'global',
  },
  { key: 'chrome_screenshot', flag: '--chrome-screenshot', value: 'bool', scope: 'global' },
  { key: 'research_depth', flag: '--research-depth', value: 'number', scope: 'global' },
  { key: 'search_time_range', flag: '--search-time-range', value: 'string', scope: 'global' },
  { key: 'bypass_csp', flag: '--bypass-csp', value: 'bool', scope: 'global' },
  { key: 'accept_invalid_certs', flag: '--accept-invalid-certs', value: 'bool', scope: 'global' },
  { key: 'screenshot_full_page', flag: '--screenshot-full-page', value: 'bool', scope: 'global' },
  { key: 'viewport', flag: '--viewport', value: 'string', scope: 'global' },
] as const

/**
 * Current web executor constraints (`crates/web/execute.rs`).
 */
export const WEB_EXECUTOR_ALLOWED_MODES = [
  'scrape',
  'crawl',
  'map',
  'extract',
  'search',
  'research',
  'embed',
  'debug',
  'doctor',
  'query',
  'retrieve',
  'ask',
  'evaluate',
  'suggest',
  'sources',
  'domains',
  'stats',
  'status',
  'dedupe',
  'github',
  'reddit',
  'youtube',
  'sessions',
  'screenshot',
] as const

export const WEB_EXECUTOR_ASYNC_MODES = [
  'crawl',
  'extract',
  'embed',
  'github',
  'reddit',
  'youtube',
] as const

export const WEB_EXECUTOR_FILE_AUTOLOAD_MODES = ['scrape', 'crawl'] as const

export const WEB_EXECUTOR_FLAG_PASSTHROUGH = [
  { key: 'max_pages', flag: '--max-pages' },
  { key: 'max_depth', flag: '--max-depth' },
  { key: 'limit', flag: '--limit' },
  { key: 'collection', flag: '--collection' },
  { key: 'format', flag: '--format' },
  { key: 'render_mode', flag: '--render-mode' },
  { key: 'include_subdomains', flag: '--include-subdomains' },
  { key: 'discover_sitemaps', flag: '--discover-sitemaps' },
  { key: 'embed', flag: '--embed' },
  { key: 'diagnostics', flag: '--diagnostics' },
] as const

export const MODE_PICKER_COMMANDS = [
  'scrape',
  'crawl',
  'map',
  'extract',
  'embed',
  'query',
  'ask',
  'research',
  'search',
  'evaluate',
  'doctor',
  'sources',
  'domains',
  'stats',
  'status',
  'suggest',
] as const
