"""Markdown renderer for MCP schema documentation.

Takes parsed struct/enum definitions and produces the full
MCP-TOOL-SCHEMA.md content.
"""

from __future__ import annotations

from datetime import datetime, timezone

from mcp_schema_models import (
    CRAWL_FIELD_DESCRIPTIONS,
    RUNTIME_ENV_VARS,
    STRUCT_TO_ACTION,
    EnumDef,
    StructDef,
)


def generate_markdown(
    structs: dict[str, StructDef],
    enums: dict[str, EnumDef],
) -> str:
    """Produce the full MCP-TOOL-SCHEMA.md content."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = []

    def emit(text: str = "") -> None:
        lines.append(text)

    _emit_header(emit, today)
    _emit_contract(emit)
    _emit_success_envelope(emit)
    _emit_parser_rules(emit)

    # Classify actions
    lifecycle_actions, direct_actions = _classify_actions(structs)

    _emit_preferred_client_actions(emit, lifecycle_actions, direct_actions)
    _emit_response_policy(emit)
    _emit_direct_actions(emit, direct_actions, structs)
    _emit_crawl_parameters(emit, structs)
    _emit_refresh_parameters(emit)
    _emit_lifecycle_families(emit, lifecycle_actions, structs, enums)
    _emit_ingest_source_types(emit, enums)
    _emit_sessions_ingest_options(emit, structs)
    _emit_artifacts_subactions(emit, enums, structs)
    _emit_enum_values(emit, enums)
    _emit_pagination(emit)
    _emit_mcp_resources(emit)
    _emit_runtime_dependencies(emit)
    _emit_error_semantics(emit)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Section emitters
# ---------------------------------------------------------------------------


def _emit_header(emit, today: str) -> None:
    emit("# Axon MCP Tool Schema (Source of Truth)")
    emit(f"Last Modified: {today}")
    emit()
    emit(
        "<!-- AUTO-GENERATED by scripts/generate_mcp_schema_doc.py — do not edit manually -->"
    )
    emit()


def _emit_contract(emit) -> None:
    emit("## Contract")
    emit("- MCP server binary: `axon-mcp`")
    emit("- Tool count: `1`")
    emit("- Tool name: `axon`")
    emit("- Primary route field: `action`")
    emit("- Canonical route form: `action` + optional `subaction`")
    emit(
        "- Response control field: `response_mode` (`path|inline|both`, default `path`)"
    )
    emit()
    emit("Code references:")
    emit("- `crates/mcp/schema.rs`")
    emit("- `crates/mcp/server.rs`")
    emit()


def _emit_success_envelope(emit) -> None:
    emit("## Canonical Success Envelope")
    emit("```json")
    emit("{")
    emit('  "ok": true,')
    emit('  "action": "<resolved action>",')
    emit('  "subaction": "<resolved subaction>",')
    emit('  "data": { "...": "..." }')
    emit("}")
    emit("```")
    emit()


def _emit_parser_rules(emit) -> None:
    emit("## Parser Rules")
    emit("Incoming request map is parsed strictly with serde:")
    emit()
    emit("- `action` is required and must match canonical schema names")
    emit(
        "- `subaction` is required for lifecycle families "
        "(`crawl|extract|embed|ingest|refresh|artifacts`)"
    )
    emit("- No fallback fields (`command`, `op`, `operation`)")
    emit("- No token normalization or case folding")
    emit("- No action alias remapping")
    emit()


def _emit_preferred_client_actions(
    emit, lifecycle_actions: list[str], direct_actions: list[str]
) -> None:
    emit("## Preferred Client Actions")
    emit("Use CLI-identical top-level actions:")
    lifecycle_str = ", ".join(f"`{a}`" for a in sorted(lifecycle_actions))
    direct_str = ", ".join(f"`{a}`" for a in sorted(direct_actions))
    emit(f"- Lifecycle families: {lifecycle_str}")
    emit(f"- Direct actions: {direct_str}")
    emit()
    emit(
        "For lifecycle management (`status|cancel|list|cleanup|clear|recover`), "
        "use canonical families with `subaction`. "
        "`refresh` also supports `schedule` subaction with `schedule_subaction` param "
        "(`list`, `create`, `delete`, `enable`, `disable`):"
    )
    emit()
    emit("```json")
    emit('{ "action": "ingest", "subaction": "status", "job_id": "..." }')
    emit("```")
    emit()


def _emit_response_policy(emit) -> None:
    emit("## Response Policy (Context-Safe Defaults)")
    emit("- Default is artifact-first (`response_mode=path`).")
    emit("- Heavy operations write result artifacts to `.cache/axon-mcp/`.")
    emit("- Tool response returns compact metadata only by default:")
    emit("  - `path`, `bytes`, `line_count`, `sha256`, `preview`, `preview_truncated`")
    emit("- Inline modes are capped/truncated and always include artifact pointers.")
    emit()


def _emit_direct_actions(
    emit, direct_actions: list[str], structs: dict[str, StructDef]
) -> None:
    emit("## Direct Actions")
    emit("These actions do not require `subaction`:")
    emit()
    emit("| Action | Required Fields | Optional Fields |")
    emit("|--------|----------------|-----------------|")
    for action in sorted(direct_actions):
        struct_name = _action_to_struct(action)
        sdef = structs.get(struct_name)
        if not sdef:
            continue
        required = sdef.required_fields()
        optional = sdef.optional_fields()
        req_str = ", ".join(f"`{f.name}` ({f.display_type})" for f in required) or "--"
        opt_str = ", ".join(f"`{f.name}`" for f in optional) or "--"
        emit(f"| `{action}` | {req_str} | {opt_str} |")
    emit()


def _emit_crawl_parameters(emit, structs: dict[str, StructDef]) -> None:
    emit("## Crawl Start Parameters")
    emit(
        'Optional fields accepted on `{ "action": "crawl", "subaction": "start", ... }`:'
    )
    emit()
    emit("| Field | Type | Default | Description |")
    emit("|-------|------|---------|-------------|")
    crawl_struct = structs.get("CrawlRequest")
    if crawl_struct:
        for f in crawl_struct.optional_fields():
            if f.name in ("job_id", "limit", "offset", "response_mode"):
                continue  # Common lifecycle fields, not crawl-specific
            desc_info = CRAWL_FIELD_DESCRIPTIONS.get(f.name)
            default = desc_info[0] if desc_info else "--"
            desc = desc_info[1] if desc_info else ""
            emit(f"| `{f.name}` | {f.display_type} | {default} | {desc} |")
    emit()


def _emit_refresh_parameters(emit) -> None:
    emit("## Refresh Start Parameters")
    emit("`refresh` accepts either form:")
    emit("- `url` (string) -- single URL refresh")
    emit("- `urls` (string[]) -- batch URL refresh")
    emit()
    emit(
        "For scheduled refreshes: "
        '`{ "action": "refresh", "subaction": "schedule", '
        '"schedule_subaction": "list|create|delete|enable|disable", '
        '"schedule_name": "..." }`'
    )
    emit()


def _emit_lifecycle_families(
    emit,
    lifecycle_actions: list[str],
    structs: dict[str, StructDef],
    enums: dict[str, EnumDef],
) -> None:
    emit("## Lifecycle Action Families")
    for action in sorted(lifecycle_actions):
        struct_name = _action_to_struct(action)
        sdef = structs.get(struct_name)
        if not sdef:
            continue
        enum_name = sdef.subaction_enum_name
        edef = enums.get(enum_name, None) if enum_name else None
        subactions = "|".join(edef.snake_variants()) if edef else "?"
        start_fields = _start_requirement_summary(action, sdef)
        emit(f"- `{action}`: `{subactions}` -- {start_fields}")
    emit()


def _emit_ingest_source_types(emit, enums: dict[str, EnumDef]) -> None:
    emit("## Ingest Source Types")
    ingest_enum = enums.get("IngestSourceType")
    if ingest_enum:
        emit()
        emit("| Source Type | Description |")
        emit("|------------|-------------|")
        source_descriptions: dict[str, str] = {
            "github": "Ingest GitHub repo (code, issues, PRs, wiki)",
            "reddit": "Ingest subreddit posts/comments",
            "youtube": "Ingest YouTube video transcript via yt-dlp",
            "sessions": "Ingest AI session exports (Claude/Codex/Gemini)",
        }
        for v in ingest_enum.snake_variants():
            desc = source_descriptions.get(v, "")
            emit(f"| `{v}` | {desc} |")
    emit()


def _emit_sessions_ingest_options(emit, structs: dict[str, StructDef]) -> None:
    sessions_struct = structs.get("SessionsIngestOptions")
    if sessions_struct:
        emit("### Sessions Ingest Options")
        emit(
            "When `source_type` is `sessions`, the optional `sessions` object accepts:"
        )
        emit()
        emit("| Field | Type | Description |")
        emit("|-------|------|-------------|")
        for f in sessions_struct.fields:
            emit(f"| `{f.name}` | {f.display_type} | -- |")
        emit()


def _emit_artifacts_subactions(
    emit, enums: dict[str, EnumDef], structs: dict[str, StructDef]
) -> None:
    emit("## Artifacts Subactions")
    artifacts_enum = enums.get("ArtifactsSubaction")
    artifacts_struct = structs.get("ArtifactsRequest")
    if artifacts_enum:
        emit(f"Subactions: `{'|'.join(artifacts_enum.snake_variants())}`")
        emit()
    if artifacts_struct:
        emit("`artifacts` fields:")
        emit("- `path` (required)")
        emit("- `pattern` (required for `grep`)")
        emit("- `limit` and `offset` for paginated inspection")
    emit()


def _emit_enum_values(emit, enums: dict[str, EnumDef]) -> None:
    emit("## Enum Values")
    emit()
    user_enums = [
        "ResponseMode",
        "McpRenderMode",
        "SearchTimeRange",
        "IngestSourceType",
    ]
    for enum_name in user_enums:
        edef = enums.get(enum_name)
        if not edef:
            continue
        emit(f"### `{enum_name}`")
        emit(f"Values: `{'|'.join(edef.snake_variants())}`")
        emit()


def _emit_pagination(emit) -> None:
    emit("## Pagination Defaults")
    emit(
        "List/search style endpoints default to low limits and accept `limit` + `offset`."
    )
    emit()


def _emit_mcp_resources(emit) -> None:
    emit("## MCP Resources")
    emit("Implemented resource(s):")
    emit("- `axon://schema/mcp-tool`")
    emit()


def _emit_runtime_dependencies(emit) -> None:
    emit("## Runtime Dependencies")
    emit("No MCP-specific env namespace. Server reads existing Axon stack vars:")
    for var in RUNTIME_ENV_VARS:
        emit(f"- `{var}`")
    emit()


def _emit_error_semantics(emit) -> None:
    emit("## Error Semantics")
    emit("- Input or shape failures -> MCP `invalid_params`")
    emit("- Runtime failures -> MCP `internal_error`")
    emit()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _classify_actions(
    structs: dict[str, StructDef],
) -> tuple[list[str], list[str]]:
    """Split actions into lifecycle (has subaction) and direct (no subaction)."""
    lifecycle_actions: list[str] = []
    direct_actions: list[str] = []
    for struct_name, action in sorted(STRUCT_TO_ACTION.items(), key=lambda x: x[1]):
        sdef = structs.get(struct_name)
        if sdef and sdef.has_subaction:
            lifecycle_actions.append(action)
        else:
            direct_actions.append(action)
    return lifecycle_actions, direct_actions


def _action_to_struct(action: str) -> str:
    """Convert action name back to struct name."""
    for struct_name, act in STRUCT_TO_ACTION.items():
        if act == action:
            return struct_name
    return ""


def _start_requirement_summary(action: str, sdef: StructDef) -> str:
    """Summarize what the 'start' subaction requires."""
    match action:
        case "crawl":
            return "start requires `urls` (array)"
        case "extract":
            return "start requires `urls` (array)"
        case "embed":
            return "start requires `input` (string)"
        case "ingest":
            return "start requires `source_type` + `target`"
        case "refresh":
            return "start accepts `url` or `urls`"
        case "artifacts":
            return "requires `path`; `pattern` for grep"
        case _:
            req = sdef.required_fields()
            if req:
                return "requires " + ", ".join(f"`{f.name}`" for f in req)
            return "no required fields"
